name: Context

on:
  schedule:
    - cron: "35 8 * * *"
  workflow_dispatch:

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Send context
        env:
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          TG_TOKEN: ${{ secrets.TG_TOKEN_MLB }}
        run: python context.py
